# Interval between backups in minutes
backup_interval_minutes: 60

# Maximum number of backups to keep
max_backups: 5

# Server autosave interval in minutes
autosave_interval_minutes: 10

# Plugin messages.
messages:
  autosave_start_broadcast: "&e[AutoSaveBackup] Server is saving all worlds..."
  autosave_complete_broadcast: "&a[AutoSaveBackup] Server autosave complete!"